let myBread = SandwichMaker.getBread();
	console.log("myBread", myBread);
let myMeat = SandwichMaker.getMeat();
	console.log("myMeat", myMeat);
let myVeggies = SandwichMaker.getVeggies();
	console.log("myVeggies", myVeggies);
let myCheese = SandwichMaker.getCheese();
	console.log("myCheese", myCheese);
let myCondiments = SandwichMaker.getCondiments();
	console.log("myCondiments", myCondiments);